---
title: "Untitled"
author: "Barbara Rose Hoover"
date: "2/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(tseries)
library(forecast)
library(sf)
library(leaflet)
```

```{r}
ca_county<-read_sf(dsn = ".", layer = "california_county_shape_file") %>% 
    select(NAME, geometry)# Read data
st_crs(ca_county)=4326
```

```{r}
nps<-read_sf(dsn = ".", layer = "nps_boundary")

nps_ca<-nps %>% 
  filter(STATE=="CA") 

nps_ca$UNIT_TYPE<-as.factor(nps_ca$UNIT_TYPE)
```

```{r}
factpal <- colorFactor(topo.colors(8), nps_ca$UNIT_TYPE) #choosing palette for polygon golors.
#I chose to use the park type as the color, however this can be by individual park, or whatever you choose 

nps_ca_map <-nps_ca %>% 
                  leaflet() %>% 
                  addTiles() %>% 
                  addPolygons(fillColor = ~factpal(UNIT_TYPE), #color of each polygon
                              fillOpacity = 1, #the opacity of the polygons
                              stroke = TRUE, #whether to outline the park boundaries,
                              color = "black",#color of polygon boundaries 
                              weight = 0.2, #stroke width in pixels
                              opacity = 1, #stroke opacity 
                              label = nps_ca$PARKNAME, #label of park when you hover over it
                              highlightOptions = highlightOptions(color = "white", weight = 5, bringToFront = TRUE),
                              labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"),
                                                          textsize = "15px",direction = "auto")) %>% #how the park name shows up when you hover over it

                  addLegend("bottomright", pal = factpal, values = ~UNIT_TYPE,
                            title = "Park Classification", 
                            opacity = 1)
                              
nps_ca_map
```
b) Alternatively, you can use the ca_county data to draw lines for the basemap. 
```{r}
factpal <- colorFactor(topo.colors(8), nps_ca$UNIT_TYPE) #choosing palette for polygon golors.
#I chose to use the park type as the color, however this can be by individual park, or whatever you choose 

nps_ca_map <-nps_ca %>% 
                  leaflet() %>% 
                  addPolylines(data=ca_county, 
                               color = "black",
                              weight = 0.3) %>% 
                  addPolygons(fillColor = ~factpal(UNIT_TYPE), #color of each polygon
                              fillOpacity = 1, #the opacity of the polygons
                              stroke = TRUE, #whether to outline the park boundaries,
                              color = "black",#color of polygon boundaries 
                              weight = 0.2, #stroke width in pixels
                              opacity = 1, #stroke opacity 
                              label = nps_ca$PARKNAME, #label of park when you hover over it
                              highlightOptions = highlightOptions(color = "white", weight = 5, bringToFront = TRUE),
                              labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"),
                                                          textsize = "15px",direction = "auto")) %>% #how the park name shows up when you hover over it

                  addLegend("bottomright", pal = factpal, values = ~UNIT_TYPE,
                            title = "California National Parks", 
                            opacity = 1)
                              
nps_ca_map
```

